version: '3'
services:
  nominatim_geocoder:
    container_name: nominatim_geocoder
    image: mediagis/nominatim:4.0
    restart: always
    shm_size: 16gb
    environment:
      #- PBF_URL=https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
      - PBF_PATH=/nominatim/data/planet-latest.osm.pbf
      - FREEZE=true
      - IMPORT_WIKIPEDIA=true
      - IMPORT_US_POSTCODES=true
      - IMPORT_GB_POSTCODES=true
      - NOMINATIM_PASSWORD=250be763b7
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/.data:/var/lib/postgresql/12/main
      - ${PWD}/.flatnode:/nominatim/flatnode
      - ${PWD}/.data_osm:/nominatim/data

#volumes:
#  nominatim-data:
